apiVersion: v1
kind: PersistentVolume
metadata:
  name: gce-pv
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: gce-pv-disk
    fsType: ext4
