apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gce-pvc
spec:
  storageClassName: manual
  volumeName: gce-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
