apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  rules:
  - http:
      paths:
      - path: /api(/|$)(.*)
        backend:
          serviceName: api-cluster-ip-service
          servicePort: 8080
      - path: /upload(/|$)(.*)
        backend:
          serviceName: fileupload-cluster-ip-service
          servicePort: 8100
      - path: /stream(/|$)(.*)
        backend:
          serviceName: stream-cluster-ip-service
          servicePort: 80
