export const SERVER_IP = 'https://groov.space';
export const categoryObject = {
  morning: [
    ['tag', 'YELLA', '오늘의 아티스트 추천: YELLA'],
    ['tag', 'music', '상쾌한 아침을 여는 음악'],
    ['hottest', '', `Charts: Groove's Weekly`],
    ['genre', 'lofi', 'Lofi'],
    ['genre', 'beats', 'Beats'],
    ['genre', 'Dept music', 'Dept music'],
    ['genre', 'rock', 'Rock'],
    ['tag', 'BayLEE', 'Artist: BayLEE'],
    ['tag', 'lypla', 'Artist: Lypla'],
    ['tag', 'jazz', 'Jazz'],
  ],
  afternoon: [
    ['tag', 'YELLA', '오늘의 아티스트 추천: YELLA'],
    ['tag', '인디', '나른한 오후를 위한 음악'],
    ['newest', '', `what's new in Groove?`],
    ['tag', 'Newage', 'Newage'],
    ['tag', 'study', 'Study'],
    ['tag', 'MonstaX', 'Artist: MonstaX'],
    ['tag', 'ESBEE', 'Artist: ESBEE'],
    ['tag', 'Soul', 'Soul'],
    ['genre', 'pH-1', 'Artist: pH-1'],
    ['genre', 'lofi', 'Lofi'],
    ['genre', 'balad', 'Balad'],
  ],
  night: [
    ['hottest', '', 'Charts: Hottest'],
    ['tag', 'Mixtape', 'Night Party Music'],
    ['genre', 'Paloalto', '오늘의 아티스트 추천: Paloalto'],
    ['tag', 'lypla', 'Artist: Lypla'],
    ['genre', 'R&B', 'R&B'],
    ['tag', 'acoustic', 'Acoustic'],
    ['genre', 'balad', 'Balad'],
    ['tag', 'BayLEE', 'Artist: BayLEE'],
    ['tag', 'YELLA', 'Artist: YELLA'],
  ],
  dawn: [
    ['tag', 'YELLA', '오늘의 아티스트 추천: YELLA'],
    ['tag', 'mood', '새벽 감성 음악'],
    ['newest', '', 'Charts: Newest'],
    ['genre', 'lofi', 'Lofi'],
    ['tag', 'study', 'Study'],
    ['tag', 'MonstaX', 'Artist: MontsaX'],
    ['tag', 'ESBEE', 'Artist: ESBEE'],
    ['tag', 'Soul', 'Soul'],
    ['genre', 'pH-1', 'Artist: pH-1'],
  ],
};
